- hosts: webservers
  user: root
  gather_facts: no

  tasks:
    - name: fire up openconnect server!
      docker_container:
        name: ocserv
        image: tommylau/ocserv
        ports:
          - "443:443"
          - "443:443/udp"
        detach: yes
        privileged: yes
