- hosts: webservers
  user: root

  tasks:
    - name: fire up openconnect server!
      docker_container:
        name: ovserv
        image: tommylau/ocserv
        ports:
          - "443:443"
          - "443:443/udp"
        detach: yes
        privileged: yes
