---
- hosts: vpnservers
  user: ubuntu
  gather_facts: no
  vars_files:
    - ../vars/ssrn_vars.yml

  vars_prompt:
    - name: password
      prompt: password?

    - name: port
      prompt: port number?
      private: no

  tasks:
    - name: install some requirements with apt
      become: true
      apt:
        install_recommends: no
        pkg:
          - build-essential
          - autoconf
          - libtool
          - asciidoc
          - xmlto
          - git
          - gcc
          - g++
          - gdb
          - cmake
          - automake
          - gcc-multilib
          - python3-pexpect

    - name: fix broken packages
      become: true
      apt:
        state: fixed
    
    - name: get user
      command: whoami
      register: user

    - name: clone the ShadowsocksR-native repo
      git:
        repo: 'https://github.com/ShadowsocksR-Live/shadowsocksr-native.git'
        clone: yes
        dest: /home/{{ user.stdout }}/ssr-n
        track_submodules: true

    - name: git submodule update --init
      command: git submodule update --init
      args:
        chdir: /home/{{ user.stdout }}/ssr-n

    - name: git submodule foreach
      command: git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'
      args:  
        chdir: /home/{{ user.stdout }}/ssr-n

    - name: create build directory
      file:
        path: /home/{{ user.stdout }}/ssr-n/build
        state: directory

    - name: build ShadowsocksR-native - CMake
      command: cmake ..
      args:
        chdir: /home/{{ user.stdout }}/ssr-n/build

    - name: build ShadowsocksR-native - Make
      make:
        chdir: /home/{{ user.stdout }}/ssr-n/build

    - name: build 32-bit binary - CMake
      command: cmake -D CMAKE_C_FLAGS=-m32 ..
      args:
        chdir: /home/{{ user.stdout }}/ssr-n/build

    - name: build 32-bit binary - Make
      make:
        chdir: /home/{{ user.stdout }}/ssr-n/build

    - name: remove build directory
      file:
        path: /home/{{ user.stdout }}/ssr-n/build
        state: absent
    
    - name: download deploy script
      get_url:
        url: https://raw.githubusercontent.com/mhbahmani/vpn-host-config-playbook/master/shadowsocksr/ssrn-install.sh
        dest: /home/{{ user.stdout }}/ssr-n/ssrn-install.sh
      args:
        creates: ssrn-install.sh
        chdir: /home/{{ user.stdout }}/ssr-n

    - name: changing perm of ssrn-install.sh
      file:
        dest: /home/{{ user.stdout }}/ssr-n/ssrn-install.sh
        mode: +x

    - name: install pexpect
      pip:
        name: pexpect

    - name: deploy
      expect:
        command: /home/{{ user.stdout }}/ssr-n/ssrn-install.sh
        responses:
          '\(Default password: .*\):': "{{ password }}"
          '\(Default port: .*\):': "{{ port }}"
          'Which cipher you would select\(Default: .*\):': "{{ cipher }}"
          'Which protocol you would select\(Default: .*\)': "{{ protocol }}" 
          'Which obfs you would select\(Default: .*\):': "{{ obfs }}"
